# GROUP 10: University of Vienna – Business Intelligence 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
#https://sqlpey.com/python/top-3-methods-to-open-csv-files-in-data-folders-using-pandas-with-relative-paths/
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
income_data = pd.read_csv("../data/raw/vie-bez-biz-ecn-inc-sex-2002f.csv", sep=";", skiprows=1, dtype=str)
unemployment_data = pd.read_csv("../data/raw/vie-bez-biz-emp-sex-uep-2002f.csv", sep=";", skiprows=1, dtype=str)
district_data = pd.read_csv("../data/raw/vie-bez-biz-pop-den-2002f.csv", sep=";", skiprows=1, dtype=str)

In [3]:
income_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,INC_TOT_VALUE,INC_MAL_VALUE,INC_FEM_VALUE,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,AT13,90000,90000,2002,20021231,18.217,20.709,15.424,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AT13,90100,90100,2002,20021231,25.463,31.961,18.536,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AT13,90200,90200,2002,20021231,16.439,18.301,14.282,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AT13,90300,90300,2002,20021231,18.701,21.444,15.804,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AT13,90400,90400,2002,20021231,20.325,23.641,16.876,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
unemployment_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,SEX,UEP_VALUE,UEP_DENSITY,Unnamed: 8,Unnamed: 9
0,AT13,90000,90000,2002,2002,0,74.894,"67,83",NaN,NaN
1,AT13,90100,90100,2002,2002,0,433,"35,32",NaN,NaN
2,AT13,90200,90200,2002,2002,0,4.784,"76,98",NaN,NaN
3,AT13,90300,90300,2002,2002,0,3.957,"68,25",NaN,NaN
4,AT13,90400,90400,2002,2002,0,1.140,"55,68",NaN,NaN

In [5]:
district_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,POP_VALUE,AREA,POP_DENSITY,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,AT13,90000,90000,2002,20020101,1.571.123,"414,87","3787,02",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AT13,90000,90000,2003,20030101,1.592.846,"414,87","3839,38",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AT13,90000,90000,2004,20040101,1.610.410,"414,87","3881,71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AT13,90000,90000,2005,20050101,1.632.569,"414,87","3935,12",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AT13,90000,90000,2006,20060101,1.652.449,"414,87","3983,04",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Preprocessing

### EDA

In [6]:
#Check how many states
print(income_data["NUTS"].unique())
print(unemployment_data["NUTS"].value_counts()) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html
#Assumed to be a data quality issue. Its only one row and should be AT13
print(district_data["NUTS"].unique())

['AT13']
NUTS
AT13    1583
AT12       1
Name: count, dtype: int64
['AT13']

In [7]:
#Check if both REF_YEAR and REF_DATE have the same values for unemployment_data
unemployment_data["REF_YEAR"].equals(unemployment_data["REF_DATE"]) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html

True

In [8]:
#Check if both REF_YEAR and REF_DATE have the same year for income_data
income_data["REF_YEAR"].astype(str).equals(income_data["REF_DATE"].astype(str).str[:4]) #https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe

True

In [9]:
year_min = min(
    income_data["REF_YEAR"].min(), 
    unemployment_data["REF_YEAR"].min(), 
    district_data["REF_YEAR"].min()
)
year_min = int(year_min)
year_min

2002

In [10]:
year_max = max(
    income_data["REF_YEAR"].max(), 
    unemployment_data["REF_YEAR"].max(),
    district_data["REF_YEAR"].max()
)
year_max = int(year_max)
year_max

2025

In [11]:
#Check if both DISTRICT_CODE and SUB_DISTRICT_CODE have the same values for income_data
income_data["DISTRICT_CODE"].equals(income_data["SUB_DISTRICT_CODE"]) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html

True

In [12]:
#Check if both DISTRICT_CODE and SUB_DISTRICT_CODE have the same values for unemployment_data
unemployment_data["DISTRICT_CODE"].equals(unemployment_data["SUB_DISTRICT_CODE"]) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html

True

### Fixing data quality issues

In [13]:
unemployment_data["NUTS"] = unemployment_data["NUTS"].str.replace('AT12', 'AT13') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
print(unemployment_data["NUTS"].unique())

['AT13']

In [14]:
unemployment_data["UEP_VALUE"] = unemployment_data["UEP_VALUE"].str.strip()

### Keep only relevant columns

In [15]:
#income_data
income_data = income_data[['NUTS', 'DISTRICT_CODE', 'REF_YEAR', 'INC_MAL_VALUE', 'INC_FEM_VALUE']] #https://stackoverflow.com/questions/11285613/selecting-multiple-columns-in-a-pandas-dataframe
income_data.head()

   NUTS DISTRICT_CODE REF_YEAR INC_MAL_VALUE INC_FEM_VALUE
0  AT13         90000     2002        20.709        15.424
1  AT13         90100     2002        31.961        18.536
2  AT13         90200     2002        18.301        14.282
3  AT13         90300     2002        21.444        15.804
4  AT13         90400     2002        23.641        16.876

In [16]:
#unemployment_data
unemployment_data = unemployment_data[['NUTS','DISTRICT_CODE', 'REF_YEAR', 'SEX', 'UEP_VALUE', 'UEP_DENSITY']] #https://stackoverflow.com/questions/11285613/selecting-multiple-columns-in-a-pandas-dataframe
unemployment_data.head()

   NUTS DISTRICT_CODE REF_YEAR SEX UEP_VALUE UEP_DENSITY
0  AT13         90000     2002   0    74.894      67,83
1  AT13         90100     2002   0       433      35,32
2  AT13         90200     2002   0     4.784      76,98
3  AT13         90300     2002   0     3.957      68,25
4  AT13         90400     2002   0     1.140      55,68

In [17]:
#district_data
district_data = district_data[['NUTS','DISTRICT_CODE', 'REF_YEAR', 'POP_VALUE', 'AREA']] #https://stackoverflow.com/questions/11285613/selecting-multiple-columns-in-a-pandas-dataframe
district_data.head()

   NUTS DISTRICT_CODE REF_YEAR  POP_VALUE    AREA
0  AT13         90000     2002  1.571.123  414,87
1  AT13         90000     2003  1.592.846  414,87
2  AT13         90000     2004  1.610.410  414,87
3  AT13         90000     2005  1.632.569  414,87
4  AT13         90000     2006  1.652.449  414,87

### Remove certain rows

In [18]:
#income_data
#Drop rows that are an aggregate
income_data = income_data[income_data["DISTRICT_CODE"] != "90000"] #https://www.geeksforgeeks.org/python/how-to-drop-rows-in-dataframe-by-conditions-on-column-values/

#Reset index
income_data = income_data.reset_index(drop=True) #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html

income_data.head()

   NUTS DISTRICT_CODE REF_YEAR INC_MAL_VALUE INC_FEM_VALUE
0  AT13         90100     2002        31.961        18.536
1  AT13         90200     2002        18.301        14.282
2  AT13         90300     2002        21.444        15.804
3  AT13         90400     2002        23.641        16.876
4  AT13         90500     2002        17.937        14.395

In [19]:
#unemployment_data
#Drop rows with total value of both genders
unemployment_data = unemployment_data[unemployment_data["SEX"] != "0"] #https://www.geeksforgeeks.org/python/how-to-drop-rows-in-dataframe-by-conditions-on-column-values/

#Drop rows that are an aggregate
unemployment_data = unemployment_data[unemployment_data["DISTRICT_CODE"] != "90000"] #https://www.geeksforgeeks.org/python/how-to-drop-rows-in-dataframe-by-conditions-on-column-values/

#Reset index
unemployment_data = unemployment_data.reset_index(drop=True) #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html

unemployment_data.head()

   NUTS DISTRICT_CODE REF_YEAR SEX UEP_VALUE UEP_DENSITY
0  AT13         90100     2002   1       232      38,03
1  AT13         90200     2002   1     2.933      92,67
2  AT13         90300     2002   1     2.403      83,54
3  AT13         90400     2002   1       668      66,57
4  AT13         90500     2002   1     1.734      95,56

In [20]:
#district_data
#Drop rows that are an aggregate
district_data = district_data[district_data["DISTRICT_CODE"] != "90000"] #https://www.geeksforgeeks.org/python/how-to-drop-rows-in-dataframe-by-conditions-on-column-values/

#Reset index
district_data = district_data.reset_index(drop=True) #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html

district_data.head()

   NUTS DISTRICT_CODE REF_YEAR POP_VALUE  AREA
0  AT13         90100     2002    17.630  2,87
1  AT13         90100     2003    17.541  2,87
2  AT13         90100     2004    17.384  2,87
3  AT13         90100     2005    17.294  2,87
4  AT13         90100     2006    17.285  2,87

### Format columns the right way

In [21]:
#income_data
#Extract District number
income_data['DISTRICT_CODE'] = income_data['DISTRICT_CODE'].str[1:3] #https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
#Remove thousands seperator
income_data['INC_MAL_VALUE'] = income_data['INC_MAL_VALUE'].str.replace('.', '') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
income_data['INC_FEM_VALUE'] = income_data['INC_FEM_VALUE'].str.replace('.', '') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
income_data.head()

   NUTS DISTRICT_CODE REF_YEAR INC_MAL_VALUE INC_FEM_VALUE
0  AT13            01     2002         31961         18536
1  AT13            02     2002         18301         14282
2  AT13            03     2002         21444         15804
3  AT13            04     2002         23641         16876
4  AT13            05     2002         17937         14395

In [22]:
#unemployment_data
#Extract District number
unemployment_data['DISTRICT_CODE'] = unemployment_data['DISTRICT_CODE'].str[1:3] #https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
#Remove thousands seperator
unemployment_data['UEP_VALUE'] = unemployment_data['UEP_VALUE'].str.replace('.', '') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
#Replace comma with decimal point
unemployment_data['UEP_DENSITY'] = unemployment_data['UEP_DENSITY'].str.replace(',', '.') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
unemployment_data.head()

   NUTS DISTRICT_CODE REF_YEAR SEX UEP_VALUE UEP_DENSITY
0  AT13            01     2002   1       232      38.03
1  AT13            02     2002   1      2933      92.67
2  AT13            03     2002   1      2403      83.54
3  AT13            04     2002   1       668      66.57
4  AT13            05     2002   1      1734      95.56

In [23]:
#district_data
#Extract District number
district_data['DISTRICT_CODE'] = district_data['DISTRICT_CODE'].str[1:3] #https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
#Remove thousands seperator
district_data['POP_VALUE'] = district_data['POP_VALUE'].str.replace('.', '') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
#Replace comma with decimal point
district_data['AREA'] = district_data['AREA'].str.replace(',', '.') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
district_data.head()

   NUTS DISTRICT_CODE REF_YEAR POP_VALUE  AREA
0  AT13            01     2002     17630  2.87
1  AT13            01     2003     17541  2.87
2  AT13            01     2004     17384  2.87
3  AT13            01     2005     17294  2.87
4  AT13            01     2006     17285  2.87

## Data Transformation and Integration

### Dim_Sex

In [24]:
dim_sex_data = {
    'id':["0", "1"],
    'code':["m", "f"],
    'name':["Male", "Female"],
}
dim_sex_df = pd.DataFrame(dim_sex_data)
print(dim_sex_df)
dim_sex_df.to_csv('../data/created/dim_sex_data.csv', sep=';', index=False) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv

  id code    name
0  0    m    Male
1  1    f  Female

### Dim_Time

In [25]:
dim_date_data = {
    'id':list(range(0, year_max-year_min+1,1)), #https://stackoverflow.com/questions/40706034/how-to-create-a-list-of-a-range-with-incremental-step
    'year':list(range(year_min,year_max+1,1)) #https://www.w3schools.com/python/ref_func_range.asp
}
dim_date_df = pd.DataFrame(dim_date_data) 
dim_date_df["id"] = dim_date_df["id"].astype(str) #https://stackoverflow.com/questions/17950374/converting-a-column-within-pandas-dataframe-from-int-to-string
print(dim_date_df)
dim_date_df.to_csv('../data/created/dim_date_data.csv', sep=';', index=False) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv

    id  year
0    0  2002
1    1  2003
2    2  2004
3    3  2005
4    4  2006
5    5  2007
6    6  2008
7    7  2009
8    8  2010
9    9  2011
10  10  2012
11  11  2013
12  12  2014
13  13  2015
14  14  2016
15  15  2017
16  16  2018
17  17  2019
18  18  2020
19  19  2021
20  20  2022
21  21  2023
22  22  2024
23  23  2025

### Dim_District

In [26]:
#Check how many districts
districts = income_data["DISTRICT_CODE"].unique() 
districts = list(districts) #https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html
print(districts)

['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']

In [27]:
#Creating a list of area values ordered by the district number
district_sizes = district_data["AREA"].unique().tolist() #https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html
print(district_sizes)

['2.87', '19.24', '7.40', '1.78', '2.01', '1.46', '1.61', '1.09', '2.97', '31.83', '23.26', '8.10', '37.71', '33.76', '3.92', '8.67', '11.39', '6.35', '24.94', '5.71', '44.44', '102.30', '32.06']

In [28]:
dim_district_data = {
    'id':list(range(0, len(districts), 1)), #https://stackoverflow.com/questions/40706034/how-to-create-a-list-of-a-range-with-incremental-step
    'Country':["AT"] * len(districts),
    'NUTS':["AT13"] * len(districts), #https://stackoverflow.com/questions/3459098/create-list-of-single-item-repeated-n-times
    'district':districts,
    'area_km2':district_sizes
}
dim_district_df = pd.DataFrame(dim_district_data)
dim_district_df["id"] = dim_district_df["id"].astype(str) #https://stackoverflow.com/questions/17950374/converting-a-column-within-pandas-dataframe-from-int-to-string
print(dim_district_df)
dim_district_df.to_csv('../data/created/dim_district_data.csv', sep=';', index=False) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv

    id Country  NUTS district area_km2
0    0      AT  AT13       01     2.87
1    1      AT  AT13       02    19.24
2    2      AT  AT13       03     7.40
3    3      AT  AT13       04     1.78
4    4      AT  AT13       05     2.01
5    5      AT  AT13       06     1.46
6    6      AT  AT13       07     1.61
7    7      AT  AT13       08     1.09
8    8      AT  AT13       09     2.97
9    9      AT  AT13       10    31.83
10  10      AT  AT13       11    23.26
11  11      AT  AT13       12     8.10
12  12      AT  AT13       13    37.71
13  13      AT  AT13       14    33.76
14  14      AT  AT13       15     3.92
15  15      AT  AT13       16     8.67
16  16      AT  AT13       17    11.39
17  17      AT  AT13       18     6.35
18  18      AT  AT13       19    24.94
19  19      AT  AT13       20     5.71
20  20      AT  AT13       21    44.44
21  21      AT  AT13       22   102.30
22  22      AT  AT13       23    32.06

### Fact_Economic_Indicators

#### Integrating unemployment_data

In [29]:
fact_economic_indicators_df = unemployment_data.drop(columns=['NUTS']) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

In [30]:
#Rename columns
fact_economic_indicators_df = fact_economic_indicators_df.rename(columns={ #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html
    "DISTRICT_CODE": "districtID", 
    "REF_YEAR": "dateID",
    "SEX": "sexID",
    "UEP_VALUE": "unemployment_count",
    "UEP_DENSITY": "unemployment_percentage"
})
fact_economic_indicators_df.head()

  districtID dateID sexID unemployment_count unemployment_percentage
0         01   2002     1                232                  38.03
1         02   2002     1               2933                  92.67
2         03   2002     1               2403                  83.54
3         04   2002     1                668                  66.57
4         05   2002     1               1734                  95.56

In [31]:
#Replace descriptive column values with their IDs
#https://www.geeksforgeeks.org/pandas/different-ways-to-iterate-over-rows-in-pandas-dataframe/
for i in range(fact_economic_indicators_df.shape[0]):
    
    #dateID
    year = int(fact_economic_indicators_df.loc[i,'dateID'])
    fact_economic_indicators_df.loc[i,'dateID'] = dim_date_df[dim_date_df["year"] == year]["id"].iloc[0]
    
    #sexID
    fact_economic_indicators_df.loc[i,'sexID'] = "0" if fact_economic_indicators_df.loc[i,'sexID'] == "1" else "1" #https://stackoverflow.com/questions/18669836/is-it-possible-to-write-single-line-return-statement-with-if-statement
    
    #districtID
    district = fact_economic_indicators_df.loc[i,'districtID']
    fact_economic_indicators_df.loc[i,'districtID'] = dim_district_df[dim_district_df["district"] == district]["id"].iloc[0]
    
fact_economic_indicators_df.head()

  districtID dateID sexID unemployment_count unemployment_percentage
0          0      0     0                232                  38.03
1          1      0     0               2933                  92.67
2          2      0     0               2403                  83.54
3          3      0     0                668                  66.57
4          4      0     0               1734                  95.56

#### Integrating income_data

In [32]:
#Add missing columns to the fact table
fact_economic_indicators_df["id"] = ""
fact_economic_indicators_df["avg_net_income"] = ""
fact_economic_indicators_df["population"] = ""

In [33]:
#Reorder columns
#https://stackoverflow.com/questions/53141240/pandas-how-to-swap-or-reorder-columns
fact_economic_indicators_df = fact_economic_indicators_df[[
    'id', 
    'avg_net_income', 
    'unemployment_count', 
    'unemployment_percentage',
    'population',
    'districtID',
    'sexID',
    'dateID'
]]
fact_economic_indicators_df.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,,,232,38.03,,0,0,0
1,,,2933,92.67,,1,0,0
2,,,2403,83.54,,2,0,0
3,,,668,66.57,,3,0,0
4,,,1734,95.56,,4,0,0

In [34]:
#Update fact_economic_indicators df with new data from income_data
for i in range(income_data.shape[0]):
    year = int(income_data.loc[i,'REF_YEAR'])
    district = income_data.loc[i,'DISTRICT_CODE']

    dateID = dim_date_df[dim_date_df["year"] == year]["id"].iloc[0]
    districtID = dim_district_df[dim_district_df["district"] == district]["id"].iloc[0]
    
    #Update value for male row 
    idx_male = fact_economic_indicators_df[
        (fact_economic_indicators_df["districtID"] == districtID) &
        (fact_economic_indicators_df["dateID"] == dateID) &
        (fact_economic_indicators_df["sexID"] == "0")
    ].index.values.astype(int)[0] #https://stackoverflow.com/questions/41217310/get-index-of-a-row-of-a-pandas-dataframe-as-an-integer
    
    fact_economic_indicators_df.loc[idx_male, "avg_net_income"] = income_data.loc[i,'INC_MAL_VALUE']    

    #Update value for female row     
    idx_female = fact_economic_indicators_df[
        (fact_economic_indicators_df["districtID"] == districtID) &
        (fact_economic_indicators_df["dateID"] == dateID) &
        (fact_economic_indicators_df["sexID"] == "1")
    ].index.values.astype(int)[0] #https://stackoverflow.com/questions/41217310/get-index-of-a-row-of-a-pandas-dataframe-as-an-integer
    
    fact_economic_indicators_df.loc[idx_female, "avg_net_income"] = income_data.loc[i,'INC_FEM_VALUE']

In [35]:
fact_economic_indicators_df.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,,31961,232,38.03,,0,0,0
1,,18301,2933,92.67,,1,0,0
2,,21444,2403,83.54,,2,0,0
3,,23641,668,66.57,,3,0,0
4,,17937,1734,95.56,,4,0,0

In [36]:
#Add values for id column
fact_economic_indicators_df["id"] = fact_economic_indicators_df.index #https://stackoverflow.com/questions/20461165/how-to-convert-index-of-a-pandas-dataframe-into-a-column
fact_economic_indicators_df["id"] = fact_economic_indicators_df["id"].astype(str) #https://stackoverflow.com/questions/17950374/converting-a-column-within-pandas-dataframe-from-int-to-string
fact_economic_indicators_df.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,0,31961,232,38.03,,0,0,0
1,1,18301,2933,92.67,,1,0,0
2,2,21444,2403,83.54,,2,0,0
3,3,23641,668,66.57,,3,0,0
4,4,17937,1734,95.56,,4,0,0

In [37]:
#transform unemployment_percentage to make it a real percentage, right now number of unemployed people on 1000
#https://www.w3schools.com/python/ref_string_strip.asp
fact_economic_indicators_df["unemployment_percentage"] = fact_economic_indicators_df["unemployment_percentage"].astype(float) #https://www.geeksforgeeks.org/python/how-to-convert-strings-to-floats-in-pandas-dataframe/
fact_economic_indicators_df["unemployment_percentage"] = round(fact_economic_indicators_df["unemployment_percentage"]/1000, 5) #https://www.w3schools.com/python/ref_func_round.asp
fact_economic_indicators_df.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,0,31961,232,0.03803,,0,0,0
1,1,18301,2933,0.09267,,1,0,0
2,2,21444,2403,0.08354,,2,0,0
3,3,23641,668,0.06657,,3,0,0
4,4,17937,1734,0.09556,,4,0,0

#### Integrating district_data

In [38]:
#Update fact_economic_indicators df with new data from district_data
for i in range(district_data.shape[0]):
    year = int(district_data.loc[i,'REF_YEAR'])
    district = district_data.loc[i,'DISTRICT_CODE']
    
    #Skip rows that have a year > 2023
    if year > 2023:
        continue
   
    dateID = dim_date_df[dim_date_df["year"] == year]["id"].iloc[0]
    districtID = dim_district_df[dim_district_df["district"] == district]["id"].iloc[0]
    
    #Update value for male row 
    idx_male = fact_economic_indicators_df[
        (fact_economic_indicators_df["districtID"] == districtID) &
        (fact_economic_indicators_df["dateID"] == dateID) &
        (fact_economic_indicators_df["sexID"] == "0")
    ].index.values.astype(int)[0] #https://stackoverflow.com/questions/41217310/get-index-of-a-row-of-a-pandas-dataframe-as-an-integer
    
    fact_economic_indicators_df.loc[idx_male, "population"] = district_data.loc[i,'POP_VALUE']    

    #Update value for female row     
    idx_female = fact_economic_indicators_df[
        (fact_economic_indicators_df["districtID"] == districtID) &
        (fact_economic_indicators_df["dateID"] == dateID) &
        (fact_economic_indicators_df["sexID"] == "1")
    ].index.values.astype(int)[0] #https://stackoverflow.com/questions/41217310/get-index-of-a-row-of-a-pandas-dataframe-as-an-integer
    
    fact_economic_indicators_df.loc[idx_female, "population"] = district_data.loc[i,'POP_VALUE']

In [39]:
fact_economic_indicators_df.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,0,31961,232,0.03803,17630,0,0,0
1,1,18301,2933,0.09267,89016,1,0,0
2,2,21444,2403,0.08354,82227,2,0,0
3,3,23641,668,0.06657,28975,3,0,0
4,4,17937,1734,0.09556,49785,4,0,0

In [40]:
fact_economic_indicators_df.to_csv('../data/created/fact_economic_indicators.csv', sep=';', index=False) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv