# GROUP 10: University of Vienna – Business Intelligence 1

In [1]:
import pandas as pd
import numpy as np

In [33]:
#https://sqlpey.com/python/top-3-methods-to-open-csv-files-in-data-folders-using-pandas-with-relative-paths/
income_data = pd.read_csv("../data/raw/vie-bez-biz-ecn-inc-sex-2002f.csv", sep=";", skiprows=1)
unemployment_data = pd.read_csv("../data/raw/vie-bez-biz-emp-sex-uep-2002f.csv", sep=";", skiprows=1)
district_data = pd.read_csv("../data/raw/vie-bez-biz-pop-den-2002f.csv", sep=";", skiprows=1)

In [3]:
income_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,INC_TOT_VALUE,INC_MAL_VALUE,INC_FEM_VALUE,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,AT13,90000,90000,2002,20021231,18.217,20.709,15.424,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AT13,90100,90100,2002,20021231,25.463,31.961,18.536,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AT13,90200,90200,2002,20021231,16.439,18.301,14.282,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AT13,90300,90300,2002,20021231,18.701,21.444,15.804,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AT13,90400,90400,2002,20021231,20.325,23.641,16.876,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
unemployment_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,SEX,UEP_VALUE,UEP_DENSITY,Unnamed: 8,Unnamed: 9
0,AT13,90000,90000,2002,2002,0,74.894,"67,83",NaN,NaN
1,AT13,90100,90100,2002,2002,0,433.000,"35,32",NaN,NaN
2,AT13,90200,90200,2002,2002,0,4.784,"76,98",NaN,NaN
3,AT13,90300,90300,2002,2002,0,3.957,"68,25",NaN,NaN
4,AT13,90400,90400,2002,2002,0,1.140,"55,68",NaN,NaN

In [34]:
district_data.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,POP_VALUE,AREA,POP_DENSITY,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,AT13,90000,90000,2002,20020101,1.571.123,"414,87","3787,02",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AT13,90000,90000,2003,20030101,1.592.846,"414,87","3839,38",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AT13,90000,90000,2004,20040101,1.610.410,"414,87","3881,71",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AT13,90000,90000,2005,20050101,1.632.569,"414,87","3935,12",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AT13,90000,90000,2006,20060101,1.652.449,"414,87","3983,04",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Transformation and Integration

### Dim_Sex

In [5]:
dim_sex_data = {
    'id':["0", "1"],
    'code':["m", "f"],
    'name':["Male", "Female"],
}
dim_sex_df = pd.DataFrame(dim_sex_data)
dim_sex_df.to_csv('../data/created/dim_sex_data.csv', sep=';', index=False) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv

### Dim_Time

In [6]:
#Check if both REF_YEAR and REF_DATE have the same values for unemployment_data
unemployment_data["REF_YEAR"].equals(unemployment_data["REF_DATE"]) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html

True

In [7]:
#Check if both REF_YEAR and REF_DATE have the same year for income_data
income_data["REF_YEAR"].astype(str).equals(income_data["REF_DATE"].astype(str).str[:4]) #https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe

True

In [8]:
year_min = min(income_data["REF_YEAR"].min(), unemployment_data["REF_YEAR"].min())
year_min

2002

In [9]:
year_max = max(income_data["REF_YEAR"].max(), unemployment_data["REF_YEAR"].max())
year_max

2023

In [10]:
dim_date_data = {
    'id':list(range(0, year_max-year_min+1,1)), #https://stackoverflow.com/questions/40706034/how-to-create-a-list-of-a-range-with-incremental-step
    'year':list(range(year_min,year_max+1,1)) #https://www.w3schools.com/python/ref_func_range.asp
}
dim_date_df = pd.DataFrame(dim_date_data) 
dim_date_df.to_csv('../data/created/dim_date_data.csv', sep=';', index=False) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv

### Dim_District

In [11]:
#Check if both DISTRICT_CODE and SUB_DISTRICT_CODE have the same values for income_data
income_data["DISTRICT_CODE"].equals(income_data["SUB_DISTRICT_CODE"]) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html

True

In [12]:
#Check if both DISTRICT_CODE and SUB_DISTRICT_CODE have the same values for income_data
unemployment_data["DISTRICT_CODE"].equals(unemployment_data["SUB_DISTRICT_CODE"]) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html

True

In [13]:
#Check how many states
income_data["NUTS"].unique()

array(['AT13'], dtype=object)

In [14]:
#Check how many districts
districts = income_data["DISTRICT_CODE"].astype(str).str[1:3].unique() #https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
districts = list(districts) #https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html
#remove district 00, since I assume it is the total)
districts.pop(0) #https://www.geeksforgeeks.org/python/python-removing-first-element-of-list/

'00'

In [42]:
#Creating a list of area values ordered by the district number
district_sizes = district_data["AREA"].unique().tolist()
district_sizes.pop(0) #remove aggregate value (total vienna area)

'414,87'

In [43]:
dim_district_data = {
    'id':list(range(0, len(districts), 1)), #https://stackoverflow.com/questions/40706034/how-to-create-a-list-of-a-range-with-incremental-step
    'state':[income_data["NUTS"].unique()[0]] * len(districts), #https://stackoverflow.com/questions/3459098/create-list-of-single-item-repeated-n-times
    'district':districts,
    'area_km2':district_sizes
}
dim_district_df = pd.DataFrame(dim_district_data)
dim_district_df.to_csv('../data/created/dim_district_data.csv', sep=';', index=False) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv

### Fact_Economic_Indicators

#### Integrating unemployment_data

In [16]:
#Drop rows with total value of both genders
fact_economic_indicators = unemployment_data[unemployment_data["SEX"] != 0] #https://www.geeksforgeeks.org/python/how-to-drop-rows-in-dataframe-by-conditions-on-column-values/

#Reset index
fact_economic_indicators = fact_economic_indicators.reset_index(drop=True) #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html

#Drop rows with total value of all districts
fact_economic_indicators['DISTRICT_CODE'] = fact_economic_indicators['DISTRICT_CODE'].apply(str) #https://stackoverflow.com/questions/17950374/converting-a-column-within-pandas-dataframe-from-int-to-string
fact_economic_indicators = fact_economic_indicators[fact_economic_indicators["DISTRICT_CODE"].str[1:3] != '00'] #https://www.geeksforgeeks.org/python/how-to-drop-rows-in-dataframe-by-conditions-on-column-values/

#Reset index
fact_economic_indicators = fact_economic_indicators.reset_index(drop=True) #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html
fact_economic_indicators.head()

,NUTS,DISTRICT_CODE,SUB_DISTRICT_CODE,REF_YEAR,REF_DATE,SEX,UEP_VALUE,UEP_DENSITY,Unnamed: 8,Unnamed: 9
0,AT13,90100,90100,2002,2002,1,232.000,"38,03",NaN,NaN
1,AT13,90200,90200,2002,2002,1,2.933,"92,67",NaN,NaN
2,AT13,90300,90300,2002,2002,1,2.403,"83,54",NaN,NaN
3,AT13,90400,90400,2002,2002,1,668.000,"66,57",NaN,NaN
4,AT13,90500,90500,2002,2002,1,1.734,"95,56",NaN,NaN

In [17]:
#Drop irrelevant columns
fact_economic_indicators = fact_economic_indicators.drop(['NUTS','SUB_DISTRICT_CODE', 'REF_DATE', 'Unnamed: 8', 'Unnamed: 9'], axis=1) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html
fact_economic_indicators

     DISTRICT_CODE  REF_YEAR  SEX  UEP_VALUE UEP_DENSITY
0            90100      2002    1    232.000      38,03
1            90200      2002    1      2.933      92,67
2            90300      2002    1      2.403      83,54
3            90400      2002    1    668.000      66,57
4            90500      2002    1      1.734      95,56
...            ...       ...  ...        ...         ...
1007         91900      2023    2      1.621      64,04
1008         92000      2023    2      3.394     115,03
1009         92100      2023    2      6.503     103,66
1010         92200      2023    2      5.993      78,59
1011         92300      2023    2      3.399      86,10

[1012 rows x 5 columns]

In [18]:
#Rename columns
fact_economic_indicators = fact_economic_indicators.rename(columns={ #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html
    "DISTRICT_CODE": "districtID", 
    "REF_YEAR": "dateID",
    "SEX": "sexID",
    "UEP_VALUE": "unemployment_count",
    "UEP_DENSITY": "unemployment_percentage"
})
fact_economic_indicators.head()

  districtID  dateID  sexID  unemployment_count unemployment_percentage
0      90100    2002      1             232.000                  38,03
1      90200    2002      1               2.933                  92,67
2      90300    2002      1               2.403                  83,54
3      90400    2002      1             668.000                  66,57
4      90500    2002      1               1.734                  95,56

In [19]:
#Replace descriptive column values with their IDs
#https://www.geeksforgeeks.org/pandas/different-ways-to-iterate-over-rows-in-pandas-dataframe/
for i, row in fact_economic_indicators.iterrows():
    #dateID
    year = fact_economic_indicators.loc[i,'dateID']
    fact_economic_indicators.loc[i,'dateID'] = int(dim_date_df[dim_date_df["year"] == year]["id"].iloc[0])
    
    #sexID
    fact_economic_indicators.loc[i,'sexID'] = 0 if fact_economic_indicators.loc[i,'sexID'] == 1 else 1 #https://stackoverflow.com/questions/18669836/is-it-possible-to-write-single-line-return-statement-with-if-statement
    
    #districtID
    district = fact_economic_indicators.loc[i,'districtID'][1:3]
    fact_economic_indicators.loc[i,'districtID'] = int(dim_district_df[dim_district_df["district"] == district]["id"].iloc[0])
    
fact_economic_indicators.head()

  districtID  dateID  sexID  unemployment_count unemployment_percentage
0          0       0      0             232.000                  38,03
1          1       0      0               2.933                  92,67
2          2       0      0               2.403                  83,54
3          3       0      0             668.000                  66,57
4          4       0      0               1.734                  95,56

#### Integrating income_data

In [20]:
#Add missing columns to the fact table
#https://stackoverflow.com/questions/16327055/how-to-add-an-empty-column-to-a-dataframe
fact_economic_indicators["id"] = np.nan
fact_economic_indicators["avg_net_income"] = np.nan
fact_economic_indicators["population"] = np.nan

In [21]:
#Reorder columns
#https://stackoverflow.com/questions/53141240/pandas-how-to-swap-or-reorder-columns
fact_economic_indicators = fact_economic_indicators[[
    'id', 
    'avg_net_income', 
    'unemployment_count', 
    'unemployment_percentage',
    'population',
    'districtID',
    'sexID',
    'dateID'
]]

In [22]:
#Update fact_economic_indicators df with new data from income_data
for i, row in income_data.iterrows():
    year = income_data.loc[i,'REF_YEAR']
    district = str(income_data.loc[i,'DISTRICT_CODE'].astype(str))[1:3]
    
    #Skip rows that are an average of all districts and sexes
    if district == "00":
        continue
   
    dateID = int(dim_date_df[dim_date_df["year"] == year]["id"].iloc[0])
    districtID = int(dim_district_df[dim_district_df["district"] == district]["id"].iloc[0])
    
    #Update value for male row 
    idx_male = fact_economic_indicators[
        (fact_economic_indicators["districtID"] == districtID) &
        (fact_economic_indicators["dateID"] == dateID) &
        (fact_economic_indicators["sexID"] == 0)
    ].index.values.astype(int)[0] #https://stackoverflow.com/questions/41217310/get-index-of-a-row-of-a-pandas-dataframe-as-an-integer
    
    fact_economic_indicators.loc[idx_male, "avg_net_income"] = income_data.loc[i,'INC_MAL_VALUE']    

    #Update value for female row     
    idx_female = fact_economic_indicators[
        (fact_economic_indicators["districtID"] == districtID) &
        (fact_economic_indicators["dateID"] == dateID) &
        (fact_economic_indicators["sexID"] == 1)
    ].index.values.astype(int)[0] #https://stackoverflow.com/questions/41217310/get-index-of-a-row-of-a-pandas-dataframe-as-an-integer
    
    fact_economic_indicators.loc[idx_female, "avg_net_income"] = income_data.loc[i,'INC_FEM_VALUE']

In [23]:
fact_economic_indicators.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,NaN,31.961,232.000,"38,03",NaN,0,0,0
1,NaN,18.301,2.933,"92,67",NaN,1,0,0
2,NaN,21.444,2.403,"83,54",NaN,2,0,0
3,NaN,23.641,668.000,"66,57",NaN,3,0,0
4,NaN,17.937,1.734,"95,56",NaN,4,0,0

In [24]:
#Order fact_economic_indicators first by dateID, districtiD, sexID
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html
fact_economic_indicators = fact_economic_indicators.sort_values(by=['dateID', 'districtID', 'sexID'])

#Reset index
fact_economic_indicators = fact_economic_indicators.reset_index(drop=True) #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html
fact_economic_indicators.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,NaN,31.961,232.000,"38,03",NaN,0,0,0
1,NaN,18.536,201.000,"32,64",NaN,0,1,0
2,NaN,18.301,2.933,"92,67",NaN,1,0,0
3,NaN,14.282,1.851,"60,70",NaN,1,1,0
4,NaN,21.444,2.403,"83,54",NaN,2,0,0

In [25]:
#Add values for id column
#https://stackoverflow.com/questions/20461165/how-to-convert-index-of-a-pandas-dataframe-into-a-column
fact_economic_indicators['id'] = fact_economic_indicators.index
fact_economic_indicators.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,0,31.961,232.000,"38,03",NaN,0,0,0
1,1,18.536,201.000,"32,64",NaN,0,1,0
2,2,18.301,2.933,"92,67",NaN,1,0,0
3,3,14.282,1.851,"60,70",NaN,1,1,0
4,4,21.444,2.403,"83,54",NaN,2,0,0

In [26]:
#transform unemployment_percentage to make it a real percentage, right now its on 1000 people
#https://www.w3schools.com/python/ref_string_strip.asp
fact_economic_indicators["unemployment_percentage"] = fact_economic_indicators["unemployment_percentage"].str.strip() #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.strip.html
fact_economic_indicators["unemployment_percentage"] = fact_economic_indicators["unemployment_percentage"].str.replace(',', '.') #https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-string-column-of-a-pandas-dataframe
fact_economic_indicators["unemployment_percentage"] = fact_economic_indicators["unemployment_percentage"].astype(float) #https://www.geeksforgeeks.org/python/how-to-convert-strings-to-floats-in-pandas-dataframe/
fact_economic_indicators["unemployment_percentage"] = fact_economic_indicators["unemployment_percentage"]/10

In [32]:
fact_economic_indicators["unemployment_percentage"] = fact_economic_indicators["unemployment_percentage"]/10
fact_economic_indicators.head()

,id,avg_net_income,unemployment_count,unemployment_percentage,population,districtID,sexID,dateID
0,0,31.961,232.000,3.803,NaN,0,0,0
1,1,18.536,201.000,3.264,NaN,0,1,0
2,2,18.301,2.933,9.267,NaN,1,0,0
3,3,14.282,1.851,6.070,NaN,1,1,0
4,4,21.444,2.403,8.354,NaN,2,0,0

TODO: 
- add population data per district